"""<your name of migration>

Revision ID: 2642009aa2a4
Revises: 7180fb0a89b9
Create Date: 2024-10-29 22:15:29.126899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2642009aa2a4'
down_revision: Union[str, None] = '7180fb0a89b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'medecin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('medecins', 'habilitations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medecins', sa.Column('habilitations', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointments', 'medecin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
