"""add username in medecin and secretariat

Revision ID: 2c3728acedb2
Revises: a26b1b360dab
Create Date: 2024-11-05 12:17:21.798830

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2c3728acedb2'
down_revision: Union[str, None] = 'a26b1b360dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medecins', sa.Column('username', sa.String(), nullable=True))
    op.add_column('secretariat', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('secretariat', 'username')
    op.drop_column('medecins', 'username')
    # ### end Alembic commands ###
