"""modify DossierMedical

Revision ID: 48094a305b12
Revises: f2f8da466234
Create Date: 2024-11-11 14:50:42.377652

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '48094a305b12'
down_revision: Union[str, None] = 'f2f8da466234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comptes_rendus_medicaux', sa.Column('title', sa.String(), nullable=True))
    op.add_column('comptes_rendus_medicaux', sa.Column('content', sa.String(), nullable=True))
    op.drop_column('comptes_rendus_medicaux', 'contenu')
    op.drop_column('comptes_rendus_medicaux', 'type')
    op.drop_constraint('dossiers_medicaux_cabinet_medical_id_fkey', 'dossiers_medicaux', type_='foreignkey')
    op.drop_column('dossiers_medicaux', 'cabinet_medical_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dossiers_medicaux',
                  sa.Column('cabinet_medical_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('dossiers_medicaux_cabinet_medical_id_fkey', 'dossiers_medicaux', 'cabinet_medical',
                          ['cabinet_medical_id'], ['id'])
    op.add_column('comptes_rendus_medicaux', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('comptes_rendus_medicaux', sa.Column('contenu', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('comptes_rendus_medicaux', 'content')
    op.drop_column('comptes_rendus_medicaux', 'title')
    # ### end Alembic commands ###
