"""<your name of migration>

Revision ID: 4eb5e9a41ab3
Revises: 
Create Date: 2024-10-29 19:23:50.805848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb5e9a41ab3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabinet_medical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('telecom', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medecins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rpps', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specialite', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telecom', sa.String(), nullable=True),
    sa.Column('habilitations', sa.String(), nullable=True),
    sa.Column('cabinet_medical_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cabinet_medical_id'], ['cabinet_medical.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medecins_id'), 'medecins', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('telecom', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('marital_status', sa.String(), nullable=True),
    sa.Column('managing_organization', sa.String(), nullable=True),
    sa.Column('medecin_id', sa.Integer(), nullable=True),
    sa.Column('cabinet_medical_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cabinet_medical_id'], ['cabinet_medical.id'], ),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secretariat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('habilitations', sa.String(), nullable=True),
    sa.Column('medecin_id', sa.Integer(), nullable=True),
    sa.Column('cabinet_medical_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cabinet_medical_id'], ['cabinet_medical.id'], ),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alertes_medicales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medecin_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('additional_name', sa.String(), nullable=True),
    sa.Column('telecom', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispositifs_medicaux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dossiers_administratifs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dossiers_medicaux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.Column('type_acces', sa.String(), nullable=True),
    sa.Column('cabinet_medical_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cabinet_medical_id'], ['cabinet_medical.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('other', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['other'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comptes_rendus_medicaux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_medical_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('contenu', sa.String(), nullable=True),
    sa.Column('auteur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auteur_id'], ['medecins.id'], ),
    sa.ForeignKeyConstraint(['dossier_medical_id'], ['dossiers_medicaux.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('destinataires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medecin_referecence', sa.Integer(), nullable=True),
    sa.Column('urgences', sa.Boolean(), nullable=True),
    sa.Column('contactUrgence', sa.String(), nullable=True),
    sa.Column('alerte_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alerte_id'], ['alertes_medicales.id'], ),
    sa.ForeignKeyConstraint(['medecin_referecence'], ['medecins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donnees_medicales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('valeur', sa.String(), nullable=True),
    sa.Column('unite', sa.String(), nullable=True),
    sa.Column('mesures', sa.String(), nullable=True),
    sa.Column('dispositif_medical_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dispositif_medical_id'], ['dispositifs_medicaux.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mesures_cardiaques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tension_arterielle', sa.String(), nullable=True),
    sa.Column('rythme_cardiaque', sa.String(), nullable=True),
    sa.Column('oxyometrie', sa.String(), nullable=True),
    sa.Column('dispositif_id', sa.Integer(), nullable=True),
    sa.Column('donnee_medicale_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dispositif_id'], ['dispositifs_medicaux.id'], ),
    sa.ForeignKeyConstraint(['donnee_medicale_id'], ['donnees_medicales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mesures_cardiaques')
    op.drop_table('donnees_medicales')
    op.drop_table('destinataires')
    op.drop_table('comptes_rendus_medicaux')
    op.drop_table('links')
    op.drop_table('dossiers_medicaux')
    op.drop_table('dossiers_administratifs')
    op.drop_table('dispositifs_medicaux')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('alertes_medicales')
    op.drop_table('secretariat')
    op.drop_table('patients')
    op.drop_index(op.f('ix_medecins_id'), table_name='medecins')
    op.drop_table('medecins')
    op.drop_table('cabinet_medical')
    # ### end Alembic commands ###
