"""<your name of migration>

Revision ID: 63d0a16f0cff
Revises: c8de10d5dc56
Create Date: 2024-10-29 20:30:07.543081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d0a16f0cff'
down_revision: Union[str, None] = 'c8de10d5dc56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
