"""add Observation and Dispositif_medicaux

Revision ID: 661f3f42e720
Revises: 48094a305b12
Create Date: 2024-12-15 22:36:49.925388

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '661f3f42e720'
down_revision: Union[str, None] = '48094a305b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispositif_medicaux',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('type', sa.String(), nullable=True),
                    sa.Column('interval', sa.Integer(), nullable=True),
                    sa.Column('status', sa.String(), nullable=True),
                    sa.Column('manufacturer', sa.String(), nullable=True),
                    sa.Column('serial_number', sa.String(), nullable=True),
                    sa.Column('lot_number', sa.String(), nullable=True),
                    sa.Column('manufacture_date', sa.Date(), nullable=True),
                    sa.Column('expiration_date', sa.Date(), nullable=True),
                    sa.Column('patient_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('observations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date_time', sa.DateTime(), nullable=True),
                    sa.Column('code', sa.String(), nullable=True),
                    sa.Column('value', sa.Float(), nullable=True),
                    sa.Column('unit', sa.String(), nullable=True),
                    sa.Column('status', sa.String(), nullable=True),
                    sa.Column('component_code', sa.String(), nullable=True),
                    sa.Column('component_value', sa.Float(), nullable=True),
                    sa.Column('component_unit', sa.String(), nullable=True),
                    sa.Column('device_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['device_id'], ['dispositif_medicaux.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observations')
    op.drop_table('dispositif_medicaux')
    # ### end Alembic commands ###
