"""<your name of migration>

Revision ID: 84185f0cccd1
Revises: ba2a46c3b89b
Create Date: 2024-10-29 20:36:15.776144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84185f0cccd1'
down_revision: Union[str, None] = 'ba2a46c3b89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
