"""first migration

Revision ID: aa5157c18127
Revises: 
Create Date: 2024-10-30 15:02:39.547644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa5157c18127'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabinet_medical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('telecom', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medecins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rpps', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specialite', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telecom', sa.String(), nullable=True),
    sa.Column('cabinet_medical_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cabinet_medical_id'], ['cabinet_medical.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medecins_id'), 'medecins', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('telecom', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('marital_status', sa.String(), nullable=True),
    sa.Column('managing_organization', sa.String(), nullable=True),
    sa.Column('medecin_id', sa.Integer(), nullable=True),
    sa.Column('cabinet_medical_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cabinet_medical_id'], ['cabinet_medical.id'], ),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secretariat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('habilitations', sa.String(), nullable=True),
    sa.Column('medecin_id', sa.Integer(), nullable=True),
    sa.Column('cabinet_medical_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cabinet_medical_id'], ['cabinet_medical.id'], ),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('additional_name', sa.String(), nullable=True),
    sa.Column('telecom', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dossiers_administratifs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dossiers_medicaux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.Column('type_acces', sa.String(), nullable=True),
    sa.Column('cabinet_medical_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cabinet_medical_id'], ['cabinet_medical.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('other', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['other'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comptes_rendus_medicaux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_medical_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('contenu', sa.String(), nullable=True),
    sa.Column('auteur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auteur_id'], ['medecins.id'], ),
    sa.ForeignKeyConstraint(['dossier_medical_id'], ['dossiers_medicaux.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comptes_rendus_medicaux')
    op.drop_table('links')
    op.drop_table('dossiers_medicaux')
    op.drop_table('dossiers_administratifs')
    op.drop_table('contacts')
    op.drop_table('secretariat')
    op.drop_table('patients')
    op.drop_index(op.f('ix_medecins_id'), table_name='medecins')
    op.drop_table('medecins')
    op.drop_table('cabinet_medical')
    # ### end Alembic commands ###
