"""first migration

Revision ID: c35c1a5226a1
Revises: 19ff5e8bf80c
Create Date: 2024-10-30 15:06:11.200416

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'c35c1a5226a1'
down_revision: Union[str, None] = '19ff5e8bf80c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
