"""<your name of migration>

Revision ID: c8de10d5dc56
Revises: 4eb5e9a41ab3
Create Date: 2024-10-29 19:27:33.433051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8de10d5dc56'
down_revision: Union[str, None] = '4eb5e9a41ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mesures_cardiaques_dispositif_id_fkey', 'mesures_cardiaques', type_='foreignkey')
    op.drop_column('mesures_cardiaques', 'dispositif_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mesures_cardiaques', sa.Column('dispositif_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('mesures_cardiaques_dispositif_id_fkey', 'mesures_cardiaques', 'dispositifs_medicaux', ['dispositif_id'], ['id'])
    # ### end Alembic commands ###
