"""add Observation and Dispositif_medicaux

Revision ID: d21efcec8c0b
Revises: 661f3f42e720
Create Date: 2024-12-15 22:38:42.753231

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'd21efcec8c0b'
down_revision: Union[str, None] = '661f3f42e720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
