"""change name of telephone to telecom

Revision ID: f2f8da466234
Revises: 2c3728acedb2
Create Date: 2024-11-07 16:42:14.545628

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f2f8da466234'
down_revision: Union[str, None] = '2c3728acedb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secretariat', sa.Column('telecom', sa.String(), nullable=True))
    op.drop_constraint('secretariat_medecin_id_fkey', 'secretariat', type_='foreignkey')
    op.drop_column('secretariat', 'telephone')
    op.drop_column('secretariat', 'medecin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secretariat', sa.Column('medecin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('secretariat', sa.Column('telephone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('secretariat_medecin_id_fkey', 'secretariat', 'medecins', ['medecin_id'], ['id'])
    op.drop_column('secretariat', 'telecom')
    # ### end Alembic commands ###
