services:
  db:
    image: postgres:17
    container_name: sante_db
    environment:
      POSTGRES_DB: sante_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  back:
    build: .
    volumes:
      - ./Interop/back:/app
    depends_on:
      - db
    ports:
        - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
volumes:
  postgres_data: