from .CabinetMedicalSchema import CabinetMedicalSchema
from .DispositifMedicauxSchema import DispositifMedicauxSchema
from .DispositifMedicauxSchema import DispositifMedicauxSchema, CreateDispositifMedicauxSchema
from .MedecinSchema import MedecinSchema, CreateMedecinSchema, UpdateMedecinSchema
from .ObservationSchema import ObservationSchema
from .PatientSchema import PatientSchema, ContactSchema, LinkSchema, CreatePatientSchema
from .SecretariatSchema import SecretariatSchema, CreateSecretariatSchema, UpdateSecretariatSchema
